image: gcc

stages:
    - build
    - test

before_script:
    - "apt-get update -qq"
    - "apt-get install -y -qq make"
    - "apt-get install -y -qq libsdl2*"

build:
    stage: build
    script:
        - "cd chef_d_oeuvre"        
        - "make"

test:
    stage: test
    script:
        - "cd chef_d_oeuvre"
        - "make test"
